### ISSUE TITLE
Telemetry Data

### ISSUE THREAD

**Issue by maccer28** [sghctoma/sst#24]
Is there a possibility of you sharing your same telemetry data?

**Comment by sghctoma** [comment]
Sure thing. Do you mean the raw data? I can upload my .sst files and put a link here. Or maybe I can upload a few of them as samples directly into the repo.
If you just meant the analyzed data, my instance is at https://sst.sghctoma.com/, there are lots of uploaded sessions there.

**Comment by maccer28** [comment]
Yeah some samples of files would be handy. sst and leverage curves, just to test the webapp. I just haven't got the daq built yet. Thanks

**Comment by sghctoma** [comment]
Sorry for the awful reaction time, I'm pretty swamped. Commit bd4cea260409417f23a791d7766fc2ddd3178b17 adds some sample SST files and the setup they were recorded with.
