### ISSUE TITLE
Alternative mounting solution that does not require a triangle?

### ISSUE THREAD

**Issue by andreaenistedeschi** [sghctoma/sst#26]
exploring this project, really great work!

Any alternatives for the sensors that don't require the triangle built with equal lenght rods?
On long travel up side down forks that would be really exposed to the "events" and low to the ground
Could use some lego gears and strings as reducer or directly a string potentiometer like this https://www.printables.com/model/178470

**Comment by sghctoma** [comment]
Thanks, glad you like the project!

The backend components are capable processing input from any kind of sensors with just configuration (i.e. no coding needed) if a mathematical expression can be constructed to convert raw input to millimeters. The firmware right now can only handle an _AS5600 with lesser than one rotation communicating via I2C_ situation, but it would be pretty straighforward to modify it to collect other kinds of sensor data. I would be happy to extend it, if some preliminary testing would confirm an alternative sensor as viable.

Good point on the upside-down forks,  but I have two main concerns with the string-based arrangement:
 - Could the spring wind up the string fast enough? I am seeing 4-5 m/s maximum compression speeds, but read somewhere that 8-10 m/s is also possible on a MTB.
 - Although it would certainly be less fragile, even minor impacts (e.g. small branches of a bush ) would affect the string resulting in erronous recordings.

Both of these might be non-issues in practice, but they certainly need to be considered. Up until now I did not have a good reason to experiment with this kind of setup, but the upside down forks argument is compelling enough (although the LEGO stuff is surprisingly sturdy :) ). I have a few spare AS5660's laying around, I'll try get my hands on some of these retractable badge holders, pullback toy cars, etc. to measure achievable angular velocity with these springs when I get the time.

**Comment by Finnitio** [comment]
I actually came up with another idea, that might work. 3d printers use a special alignment for an belt to keep the belt tension constant even though the carriage is moving. [This](https://reprap.org/wiki/File:CoreXY_principle.png) is a picture of such an alignment. Once i have snufi runing with the triangular version I might try to build it using a linear rail.
